image:
  repository: collabora/code
  tag: 6.4.6.2
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

service:
  port:
    port: 9980

env:  
  domain:    
  dictionaries:             
  username: admin
  password: changeme
  extra_params:
  server_name:
